spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# 에러 응답 설정
server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie

# 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug

