name: remote ssh command
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Execute Test Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: echo "hello!!"
